### PR TITLE
Milestone 3: Page Structure with Inactivity Timeout

### PR DESCRIPTION
**Pull request by abdulrauf11**
# Overview
This PR contains the following changes:

1. Inactivity timeout - The website will refresh after 60sec have passed without any activity.
2. Secondary info page - The **Learn More** button will open up a modal with an image. The image used depends on the current language of the site.
3.  Complete refactoring of the codebase to make it cleaner.
4. Removed previously used temporary styles so we can start from scratch in the next phase.
5. Used **reactstrap** for some basic styling to make the site look good without adding unnecessary lines of code. Will probably be removed in the next phase.
6. Changed component names so they are more consistent with the wording used in the _Requirement Specification_ document.

##  Libraries/Plugins
We used **react-idle-timer** to track inactivity. You look at the documentation here: https://github.com/SupremeTechnopriest/react-idle-timer

## Public Test Link
https://tsck-cochlear-implant.netlify.app/

## Preview
Screenshot 2021-04-02 at 4 39 54 PM
Screenshot 2021-04-02 at 4 40 14 PM
Screenshot 2021-04-02 at 4 40 26 PM

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Hey @tnordberg, I would also like to discuss a little about the **reactstrap** library. It was already available in the repo and we used it so that we don't have to write a lot of SCSS in this milestone.

For the next phase, however, I want to confirm if we're supposed to it or not? Are there any such restrictions?

**Comment by abdulrauf11** [comment]
NOTE: This PR does not implement animations. I know we have discussed that the popup should not flicker when it opens up, but I saw it as a design thing. It will be implemented/fixed in the next phase.

**Comment by tnordberg** [comment]
> Hey @tnordberg, I would also like to discuss a little about the **reactstrap** library. It was already available in the repo and we used it so that we don't have to write a lot of SCSS in this milestone.
> 
> For the next phase, however, I want to confirm if we're supposed to use it or not? Are there any such restrictions?

We include `reactstrap` by default because it helps us prototype layouts faster, but it is not a requirement. Feel free to keep or remove it, whichever allows you to match our designs. Thanks for checking.

**Review by tnordberg — CHANGES_REQUESTED** [review]
This is looking good! I think we've used the same inactivity package before and it works well.  

There are two changes I'd like to request before merging. I would be okay with you including these changes in the next phase, so let me know how you'd like to proceed.

1. 
Once the inactivity timeout has triggered once, the countdown should not start again until someone interacts with the interface. This is because an interface can sit inactive in an exhibit for long periods, and we don’t want the screen to be flashing every 60 seconds. Apologies for not being clearer about this in our description.

2. 
The “Learn more” modal is image-based, but that text should ideally also come from the external language file. Was this already your plan? This is so we can easily change it without re-exporting a new image. I know this would be a little more complex because of the large, styled numbers, so let me know if you think it's accomplishable.

Nice work!

**Comment by tnordberg** [comment]
@abdulrauf11 and I chatted, and Rauf Tech will address the changes as part of next milestone. They've also [opened an issue ](https://github.com/scimusmn/tsck-cochlear-implant/issues/10)to represent these changes. 

Merging!

**Pull request merged**
